### ISSUE TITLE
list.txt isnt getting generated

### ISSUE THREAD

**Issue by ghost** [phanirithvij/twist.moe#1]

**Comment by phanirithvij2000** [comment]
I'll fix it as soon as possible
Thanks for trying this
But I recommend using [anime_downloader](https://github.com/vn-ki/anime-downloader/)
If you are comfortable with python

**Comment by phanirithvij** [comment]
fixed #1 #2

**Comment by OfficialCRUGG** [comment]
Still occurring for me. On both Windows with Git Bash and Ubuntu 19
![Screenshot from 2019-10-06 21-04-55](https://user-images.githubusercontent.com/25248999/66274275-13aa6180-e87d-11e9-9682-552fdb517428.png)

**Comment by phanirithvij** [comment]
Please do `git pull` in the `TwistMoeDownloader` directory and also tell me what the output of `startp.sh gabriel-dropout` is.

**Comment by OfficialCRUGG** [comment]
Here is my Windows Output:
![image](https://user-images.githubusercontent.com/25248999/66309373-c6c09c80-e909-11e9-83fa-4a3107e35098.png)
I don't know why it says that the cryptodome module isn't existing, even though I've installed it.

Linux Output (Ubuntu 19)
![Screenshot from 2019-10-07 13-57-49](https://user-images.githubusercontent.com/25248999/66309699-8dd4f780-e90a-11e9-90b6-4dca3d58a518.png)

**Comment by phanirithvij2000** [comment]
I was able to replicate it. Let me try and figure it out.

**Comment by phanirithvij** [comment]
Hey @OfficialCRUGG how did you install the cryptodome?
You should only do it via `pip install pycryptodomex`
If you have installed it in any other way please uninstall those.
Like `pip uninstall pycrypto crypto cyptodome pycryptodome`
None of those should be installed.

**Comment by phanirithvij** [comment]
And I also made some recent changes, do a `git pull` before downloading it again.

**Comment by ghost** [comment]
Yeah BS, you fixed shit. Still doesnt work.
Edit yes i got it wrong person, nice.

**Comment by phanirithvij** [comment]
@KoroFX I suggest you stop using those words.

> Yeah BS, you fixed shit. Still doesnt work.

This isn't some paid service.

[Message](https://user-images.githubusercontent.com/29627898/71538977-8c8bf780-295a-11ea-97fa-e7f7bd5197ed.png) in case you delete it.

**Comment by ghost** [comment]
Lol @phanirithvij i wrote this on the wrong thread i got confused with the twist downloaders, yours is actually working.
Im sorry that wasnt meant for you.

**Comment by KoroFX** [comment]
And why do you link it in your message 🤣
Am i that important so everyone sees that i misstok your program with somebody elses ?
