### ISSUE TITLE
Download error (OSError: Cannot load native module)

### ISSUE THREAD

**Issue by 9HitCode** [phanirithvij/twist.moe#16]
I've spent a couple hours retrying and redoing it but i seem to be stuck in this error everything is installed properly. But don't know what is the cause of the problem 

```
D:\Twist
? bash

Christopher@Lilith  /d/Twist
$ git clone https://github.com/phanirithvij/twist.moe.git
Cloning into 'twist.moe'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 4627 (delta 6), reused 14 (delta 3), pack-reused 4607
Receiving objects: 100% (4627/4627), 7.56 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (926/926), done.

Christopher@Lilith  /d/Twist
$ cd twist.moe/

Christopher@Lilith  /d/Twist/twist.moe (master)
$ ./setup.sh
[setup.sh] > Python is installed
[setup.sh] > Version: Python 3.7.4
[setup.sh] > python3 command is not accesible from the script
[setup.sh] > pycryptodome, hashlib for python installed
```
<details>
<summary>Traceback</summary>

```python
Christopher@Lilith  /d/Twist/twist.moe (master)
$ ./startp.sh https://twist.moe/a/fate-zero
Making Anime directory..
Creating fate-zero
making it https://twist.moe/a/fate-zero/1
Fetching info...
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "../decrypt.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\Christopher\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 126] The specified module could not be found
```

</details>

```
Creating fate-zero/list.txt
copying download.sh to fate-zero
Done
Check the Anime/fate-zero folder
Enjoy
fate-zero Added to animelist.txt

Christopher@Lilith  /d/Twist/twist.moe (master)
$ cd Anime/fate-zero

Christopher@Lilith  /d/Twist/twist.moe/Anime/fate-zero (master)
$ ./download.sh
curl is installed: yes
cat: list.txt: No such file or directory
Total no of episodes : 0
Enter 'a' for all episodes
start at:
1
end at:
25
cat: list.txt: No such file or directory
```

**Comment by 9HitCode** [comment]
It might be because of 
```
[setup.sh] > python3 command is not accesible from the script
```

But as I mentioned I've restarted and clean installed  - Python, Git Bash, CMDER and the repository
Still scratching my head on what I have done wrong.

**Comment by phanirithvij** [comment]
Thanks for reporting I started a fix, you can expect it to work soon.

**Comment by phanirithvij** [comment]
I fixed it.
Just remove that directory (folder) `twist.moe` and do the repository part git clone and `./setup.sh` again.

You need not install `cmder`, `git bash`, `python` again that's a waste of time.

Let me know if you have any more issues.
You can close this issue if it was solved for you

**Comment by phanirithvij** [comment]
> For future reference

The structure of the modules `Crypto`, `pycrypto`,  `pycryptodome`,  `pycryptodomex` are the cause of this problem.

**Comment by 9HitCode** [comment]
I'm still not able to make it work

```
$ ./startp.sh
Making Anime directory..
Enter link from https://twist.moe/
https://twist.moe/a/fate-zero
Creating fate-zero
making it https://twist.moe/a/fate-zero/1
Fetching info...
rm: cannot remove '.temp.txt': No such file or directory
Traceback (most recent call last):
  File "../decrypt.py", line 10, in <module>
    from requests.utils import quote
ModuleNotFoundError: No module named 'requests'
Creating fate-zero/list.txt
copying download.sh to fate-zero
Done
Check the Anime/fate-zero folder
Enjoy
fate-zero Added to animelist.txt

```

When proceeding to the download.sh I get this error
```
$ ./download.sh
curl is installed: yes
cat: list.txt: No such file or directory
Total no of episodes : 0
Enter 'a' for all episodes
start at:
1
end at:
25
cat: list.txt: No such file or directory
```

**Comment by 9HitCode** [comment]
I've Tried it in my other PC same error :(

**Comment by phanirithvij** [comment]
I've fixed that too.
Try it again.

**Comment by 9HitCode** [comment]
So did it again. Came up with this error

```
$ ./setup.sh
[setup.sh] > Python is installed
[setup.sh] > Version: Python 3.7.4
[setup.sh] > python3 command is not accesible from the script
Requirement already up-to-date: pycryptodomex in c:\users\christopher\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 1)) (3.8.2)
Collecting hashlib (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Christopher\AppData\Local\Programs\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-l7vsjqbx\\hashlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-l7vsjqbx\\hashlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\CHRIST~1\AppData\Local\Temp\pip-install-l7vsjqbx\hashlib\
    Complete output (22 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 18, in <module>
        import setuptools.version
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
        import email.parser
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\email\parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\email\feedparser.py", line 27, in <module>
        from email._policybase import compat32
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\email\_policybase.py", line 9, in <module>
        from email.utils import _has_surrogates
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\email\utils.py", line 28, in <module>
        import random
      File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\random.py", line 46, in <module>
        from hashlib import sha512 as _sha512
      File "C:\Users\CHRIST~1\AppData\Local\Temp\pip-install-l7vsjqbx\hashlib\hashlib.py", line 80
        raise ValueError, "unsupported hash type"
                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[setup.sh] > Installing Cryptodome successful
[setup.sh] > Installing requests successful
[setup.sh] > Installing hashlib successful
[setup.sh] > pycryptodomex, hashlib, requests for python installed

```

BUT after executing download.sh so far its downloading properly. Just thought of adding the error just in case.

**Comment by phanirithvij** [comment]
@9HitCode That error is not important for now consider it as a warning instead of an error. Closing this.
